#!/bin/bash
PROGNAME=supervisord
DAEMON=/usr/local/bin/$PROGNAME
CONFIG=/etc/$PROGNAME.conf
PIDFILE=/tmp/$PROGNAME.pid
DESC="supervisord daemon"
SCRIPTNAME=/etc/init.d/$PROGNAME

test -x $DAEMON || exit0

start()
{
    echo  "Starting $DESC:$PROGNAME"
    $DAEMON -c $CONFIG
    echo "..."
}

stop()
{
    echo  "Stopping $DESC:$PROGNAME"
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    echo "..."
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:$SCRIPTNAME(start|stop|restart)" >&2
        exit 1
esac
exit 0
